# Generated by Django 5.2.7 on 2025-11-26 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pacientes',
            new_name='Paciente',
        ),
    ]
