# Generated by Django 5.2.8 on 2025-11-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('especialidad', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono Contacto')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('horario', models.TextField(help_text='Ej: Lunes a Viernes de 9:00 a 18:00', verbose_name='Horario de Atención')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
            },
        ),
    ]
